FROM python:3.12-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY shared/ ./shared/
COPY services/vehicles_service/ ./services/vehicles_service/

EXPOSE 8004

CMD ["uvicorn", "services.vehicles_service.main:app", "--host", "0.0.0.0", "--port", "8004"]
