"""Bolivian traffic monitoring locations configuration."""

BOLIVIA_LOCATIONS = [
    {
        "id": "loc-scz-001",
        "name": "Av. Cristo Redentor - Santa Cruz",
        "city": "Santa Cruz",
        "speed_limit": 60,
        "lambda_rate": 1200,
        "speed_mu": 55,
        "speed_sigma": 12,
        "coordinates": {"lat": -17.7833, "lon": -63.1821},
    },
    {
        "id": "loc-scz-002",
        "name": "Doble Via La Guardia - Santa Cruz",
        "city": "Santa Cruz",
        "speed_limit": 80,
        "lambda_rate": 900,
        "speed_mu": 70,
        "speed_sigma": 15,
        "coordinates": {"lat": -17.8667, "lon": -63.3333},
    },
    {
        "id": "loc-scz-003",
        "name": "Segundo Anillo - Av. Santos Dumont",
        "city": "Santa Cruz",
        "speed_limit": 50,
        "lambda_rate": 1400,
        "speed_mu": 42,
        "speed_sigma": 10,
        "coordinates": {"lat": -17.7856, "lon": -63.1694},
    },
    {
        "id": "loc-lpz-001",
        "name": "Autopista La Paz - El Alto",
        "city": "La Paz",
        "speed_limit": 80,
        "lambda_rate": 800,
        "speed_mu": 65,
        "speed_sigma": 14,
        "coordinates": {"lat": -16.5100, "lon": -68.1193},
    },
    {
        "id": "loc-lpz-002",
        "name": "Av. 6 de Agosto - Sopocachi",
        "city": "La Paz",
        "speed_limit": 40,
        "lambda_rate": 600,
        "speed_mu": 32,
        "speed_sigma": 8,
        "coordinates": {"lat": -16.5042, "lon": -68.1317},
    },
    {
        "id": "loc-cbba-001",
        "name": "Av. Blanco Galindo - Cochabamba",
        "city": "Cochabamba",
        "speed_limit": 70,
        "lambda_rate": 700,
        "speed_mu": 60,
        "speed_sigma": 13,
        "coordinates": {"lat": -17.3936, "lon": -66.1568},
    },
    {
        "id": "loc-cbba-002",
        "name": "Av. Heroinas - Centro",
        "city": "Cochabamba",
        "speed_limit": 40,
        "lambda_rate": 500,
        "speed_mu": 35,
        "speed_sigma": 9,
        "coordinates": {"lat": -17.3895, "lon": -66.1570},
    },
    {
        "id": "loc-scz-004",
        "name": "Av. Banzer - 4to Anillo",
        "city": "Santa Cruz",
        "speed_limit": 60,
        "lambda_rate": 1100,
        "speed_mu": 52,
        "speed_sigma": 11,
        "coordinates": {"lat": -17.7631, "lon": -63.1822},
    },
]

VIDEO_FEED_URLS = [
    "https://res.cloudinary.com/dppju38gx/video/upload/v1776782872/14468488_3840_2160_30fps_iayndn.mp4",
    "https://res.cloudinary.com/dppju38gx/video/upload/v1776782805/8321860-hd_1920_1080_30fps_zl1abc.mp4",
]
